// GENERATED by `npm run bundle:plugin` — do NOT hand-edit.
//
// `PLUGIN_BUILD` is a content hash of the sibling Figma plugin's shipped files
// (manifest + build output), recomputed every time the downloadable zip is
// re-bundled. It's the honest "did the plugin actually change" signal — it
// flips on any real change, without relying on someone bumping the semver.
//
// `PLUGIN_VERSION` is the human-readable version from the plugin's package.json,
// shown in the UI. The app compares the user's last-downloaded `PLUGIN_BUILD`
// (`pluginBuildSeen` in the store) against this to surface an "Update available"
// hint on the Sync hub's "Download plugin" row.
export const PLUGIN_VERSION = '0.2.0'
export const PLUGIN_BUILD = '178991b0851e'
