// Which semantic roles a catalogue component actually paints with — the data
// behind Inspector mode's badge.
//
// DERIVED, never listed. `COMPONENT_COLOR_FIELDS` is generated by walking each
// specimen's own call graph (`npm run gen:component-color-fields`), and
// `CATEGORICAL_FIELD_ROLE` is the same table `resolvePreviewTokens` paints
// those fields from. Composing the two means the inspector can only ever name
// a role the component genuinely reads: a hand-written list here would be a
// second claim about token usage, free to drift from the render the moment a
// specimen changed which field it reaches for — which is the exact failure the
// generator exists to prevent.
//
// The cost of deriving it is a known blind spot, stated rather than hidden:
// see `INSPECTOR_BLIND_SPOT` below.

import { COMPONENT_ARCH_ROLES, COMPONENT_COLOR_FIELDS } from './componentColorFields.generated'
import { CATEGORICAL_FIELD_ROLE } from './previewTokens'
import type { PreviewTokens } from '../components/preview/ButtonPreview'

/** Where a role was OBSERVED on the element — a fill, the ink of a glyph or
 *  a run of text, or a stroke. The badge shows it so a row reads as a place on
 *  the component rather than a name in a list. */
export type PaintSlot = 'fill' | 'ink' | 'stroke'

/**
 * A role the inspector reports for a component, with its value in the theme
 * currently on screen. `css` is whatever `archTokens` resolved — an 8-digit
 * hex for the 16 alpha-backed roles, so the badge must be able to render a
 * translucent swatch (see `TokenInspector`'s checkerboard).
 */
export interface InspectedRole {
  /** Fully qualified Categorical id — `action.primary.default`. */
  id: string
  css: string
  /** Absent when the row comes from the component's declared UNION rather
   *  than from a colour measured on the rendered element. */
  where?: PaintSlot
}

/** One element's roles, plus whether they were measured off the render. */
export interface Inspection {
  roles: InspectedRole[]
  /**
   * `false` when nothing on the element resolved to a role and `roles` is the
   * component's whole union instead — the honest wider answer, and the state
   * `INSPECTOR_BLIND_SPOT` is written for.
   */
  measured: boolean
}

/**
 * What the derivation CANNOT see, so nobody mistakes an empty badge for a
 * component that uses no colour.
 *
 * The covered path is a `PreviewTokens` field read inside `specimens.tsx`
 * (`t.brandSolid`) — the generator captures it and this module maps it back to
 * a role. Two paths escape it, and both are live today:
 *
 *  1. **Straight off the resolved map** — `t.archTokens['status.critical.border']`,
 *     which a dozen helpers in `specimens.tsx` do (`statusInk`, `statusOn`,
 *     `statusBorder`, `slotOf`). The generator records the FIELD closure, not
 *     those literal ids.
 *  2. **Through a helper in ANOTHER MODULE** — the walk is scoped to
 *     `specimens.tsx`'s own AST, so a field read inside e.g.
 *     `previewTokens.ts`'s `overlaySurfaceOf` is invisible to it. This is why
 *     Modal · Combobox · Command · ContextMenu report no `surface.page` /
 *     `surface.layer-1` despite painting with them: the specimens moved that
 *     read into `overlaySurfaceStyle`, and the generated field list narrowed
 *     to match the walk rather than the render.
 *
 * UPDATE: both escapes are closed for a MEASURED inspection — `inspectElement`
 * reads the colours off the rendered element, where an `archTokens` read and a
 * read through another module are indistinguishable from any other paint. This
 * constant is now only shown when the measurement found nothing and the badge
 * fell back to the union below (`Inspection.measured === false`), which is the
 * one state where the derivation is still the field closure.
 *
 * UPDATE 2: both escapes are now closed for the UNION too, the way this note
 * always said they should be — in the generator, not with a hardcoded
 * supplement. It collects role-id literals for (1) and walks `previewTokens.ts`
 * helpers for (2), emitting `COMPONENT_ARCH_ROLES` beside the field map;
 * `rolesForComponent` unions the two. That mattered beyond the fallback,
 * because the union is also the ALLOW-LIST a measured inspection filters
 * against (`rolesForPaints`) — so a role missing from it was dropped from the
 * badge even when the element visibly painted it. `surface.layer-2` on
 * SegmentedControl, `border.focus` on every text field and
 * `action.primary.hover` on Toggle were all in that hole.
 *
 * What REMAINS a blind spot is different in kind: a colour a specimen mixes
 * itself (`soft()`, `tintOf()`, `darken()`) exists in no ramp, so there is no
 * role to name — the fix there is the specimen binding an alpha role instead,
 * not more static analysis. It still UNDER-reports: the badge never names a
 * role a component doesn't paint, so what's listed is always true.
 */
export const INSPECTOR_BLIND_SPOT =
  'Colours a specimen mixes itself (soft washes, derived hovers) match no token, so they are not listed.'

/**
 * Field → role, inverted once. Several fields can share a role; the id is what
 * the badge shows, so duplicates collapse.
 *
 * THIS IS THE COMPONENT'S UNION, NOT THE RENDERED VARIANT.
 * `COMPONENT_COLOR_FIELDS` is the union over a specimen's whole axis matrix,
 * so a Solid Brand button reports the four `status.*` solids its
 * Danger/Success variants use too. That is the right answer to "which roles
 * does this component consume" and the wrong one to "which roles paint THIS
 * button" — `inspectElement` below answers the second by measuring the render,
 * and uses this list to disambiguate. Two jobs, two functions; don't collapse
 * them.
 */
export function rolesForComponent(componentKey: string): string[] {
  const fields = COMPONENT_COLOR_FIELDS[componentKey]
  const direct = COMPONENT_ARCH_ROLES[componentKey]
  if (!fields && !direct) return []
  const ids: string[] = []
  for (const field of fields ?? []) {
    const id = CATEGORICAL_FIELD_ROLE[field]
    if (id && !ids.includes(id)) ids.push(id)
  }
  // Roles the specimen resolves BY NAME rather than through a field —
  // `archTokenOf(t, 'surface.inverse')` and the `previewTokens` helpers. A
  // field list structurally cannot express these, and this list is used as an
  // ALLOW-LIST (`rolesForPaints`), so anything missing here is dropped from
  // the badge even when the component visibly paints it. That is what hid
  // `surface.layer-2` on SegmentedControl, `border.focus` on every text
  // field, and `action.primary.hover` on Toggle.
  for (const id of direct ?? []) {
    if (!ids.includes(id)) ids.push(id)
  }
  return ids
}

/**
 * The roles for a component, resolved against the theme on screen.
 *
 * A role with no entry in `archTokens` is DROPPED, not shown as a blank: the
 * map is populated only under the Categorical architecture, and a badge
 * listing ids with no colour beside them would imply the tokens are broken
 * rather than that the projection isn't active.
 */
export function inspectComponent(t: PreviewTokens, componentKey: string): InspectedRole[] {
  const arch = t.archTokens
  if (!arch) return []
  return rolesForComponent(componentKey)
    .map((id) => ({ id, css: arch[id] }))
    .filter((r): r is InspectedRole => !!r.css)
}

// ── Measured inspection: which roles paint THIS element ──────────────────────
//
// Pointing at one Solid button and being handed ten roles — six of which
// belong to variants that aren't on screen — is the component's answer to a
// question about a pixel. The fix is to ask the render: read the computed
// colours off the element and match them back to the theme's own resolved
// values, so a Solid Brand button reports exactly its fill and its label ink.
//
// DERIVED, like everything else here, and derived one step CLOSER to the truth
// than the field closure: a colour on screen cannot be a colour the component
// doesn't paint. It also closes half of `INSPECTOR_BLIND_SPOT` for free — a
// role read straight off `archTokens` (`status.*.border`, `surface.input`, the
// ghost washes) is invisible to the generator's AST walk but perfectly visible
// as a border colour in `getComputedStyle`.
//
// The declared union stays load-bearing for DISAMBIGUATION. Roles legitimately
// share values (`content.on-action == content.inverse`, `surface.inverse ==
// surface.overlay` in light), so one observed hex can name two roles; the one
// the component actually reads wins. Without that step a Solid button would
// report `content.inverse` beside `content.on-action` and be right twice about
// the same pixel, which is exactly the noise this is removing.

/** How many descendants to read per element. A collage module is ~40 nodes;
 *  the cap only exists so a pathological subtree can't stall a pointermove. */
const MAX_NODES = 400

const rgbaKey = (r: number, g: number, b: number, a: number) =>
  `${r},${g},${b},${a.toFixed(2)}`

/**
 * A CSS colour reduced to `r,g,b,a` so a computed style (`rgb()` / `rgba()`)
 * can be compared with a token's hex.
 *
 * Alpha is compared at two decimals, and that is exact rather than tolerant:
 * both sides descend from the same 8-bit channel — the token's `aa` and the
 * value the browser resolved from it — so they round identically.
 *
 * Fully transparent returns `null`: nothing is painted, and `transparent` is
 * what every specimen writes for "this style has no fill/stroke", so matching
 * it would report a role for the absence of one.
 */
export function normalizeColor(css: string | null | undefined): string | null {
  if (!css) return null
  const value = css.trim().toLowerCase()
  if (!value || value === 'transparent' || value === 'currentcolor' || value === 'none') return null

  if (value[0] === '#') {
    const hex = value.slice(1)
    if (hex.length !== 3 && hex.length !== 4 && hex.length !== 6 && hex.length !== 8) return null
    const short = hex.length <= 4
    const channel = (i: number) =>
      parseInt(short ? hex[i] + hex[i] : hex.slice(i * 2, i * 2 + 2), 16)
    const r = channel(0), g = channel(1), b = channel(2)
    if (!Number.isFinite(r) || !Number.isFinite(g) || !Number.isFinite(b)) return null
    const alpha = short ? hex.length === 4 : hex.length === 8
    const a = alpha ? channel(3) / 255 : 1
    return a === 0 ? null : rgbaKey(r, g, b, a)
  }

  if (!value.startsWith('rgb')) return null
  const parts = value.match(/-?[\d.]+%?/g)
  if (!parts || parts.length < 3) return null
  const channel = (raw: string) =>
    Math.round(raw.endsWith('%') ? parseFloat(raw) * 2.55 : parseFloat(raw))
  const r = channel(parts[0]), g = channel(parts[1]), b = channel(parts[2])
  const raw = parts[3]
  const a = raw == null ? 1 : (raw.endsWith('%') ? parseFloat(raw) / 100 : parseFloat(raw))
  if (![r, g, b, a].every(Number.isFinite)) return null
  return a === 0 ? null : rgbaKey(r, g, b, a)
}

/** value → role ids, built once per resolved token map. Several roles can
 *  share a value, so this is one-to-many by construction. */
const INDEX_CACHE = new WeakMap<Record<string, string>, Map<string, string[]>>()

function roleIndex(arch: Record<string, string>): Map<string, string[]> {
  const cached = INDEX_CACHE.get(arch)
  if (cached) return cached
  const index = new Map<string, string[]>()
  for (const [id, css] of Object.entries(arch)) {
    const key = normalizeColor(css)
    if (!key) continue
    const bucket = index.get(key)
    if (bucket) bucket.push(id)
    else index.set(key, [id])
  }
  INDEX_CACHE.set(arch, index)
  return index
}

/** PreviewTokens field values → role ids. A specimen often paints
 *  `t.errorColor` (the primitive ramp) while `archTokens` carries the solved
 *  projection — byte-different, same role. */
function fieldRoleIndex(
  t: PreviewTokens,
  fields: string[],
): Map<string, string[]> {
  const index = new Map<string, string[]>()
  for (const field of fields) {
    const id = CATEGORICAL_FIELD_ROLE[field]
    if (!id) continue
    const val = t[field as keyof PreviewTokens]
    if (typeof val !== 'string') continue
    const key = normalizeColor(val)
    if (!key) continue
    const bucket = index.get(key) ?? []
    if (!bucket.includes(id)) bucket.push(id)
    index.set(key, bucket)
  }
  return index
}

function parseInspectVariant(el: Element): Record<string, string> | null {
  const raw = el.getAttribute('data-inspect-variant')
  if (!raw) return null
  try {
    const parsed = JSON.parse(raw) as Record<string, string>
    return parsed && typeof parsed === 'object' ? parsed : null
  } catch {
    return null
  }
}

const STATUS_SEV: Record<string, 'critical' | 'warning' | 'success' | 'info'> = {
  Error: 'critical',
  Danger: 'critical',
  Warning: 'warning',
  Success: 'success',
  Info: 'info',
}

function buttonIntent(color?: string): string {
  if (color === 'Danger') return 'Error'
  return color ?? 'Brand'
}

function roleAt(
  arch: Record<string, string>,
  paints: { css: string; where: PaintSlot }[],
  id: string,
  where: PaintSlot,
): InspectedRole | null {
  if (!arch[id]) return null
  // Match the paint that IS this role's colour first; only fall back to
  // "the first paint in this slot" when nothing measured that value (a
  // state variant, say, where the rendered fill is the hover tone rather
  // than the role's own). Slot alone is not enough the moment a component
  // paints two of the same kind: Toast asks for `surface.inverse` AND
  // `status.<sev>.surface-solid`, both fills, and both used to resolve to
  // the first fill observed — so the severity dot's row was stamped with
  // the toast body's near-black instead of its own red.
  const want = normalizeColor(arch[id])
  const paint = paints.find((p) => p.where === where && want && normalizeColor(p.css) === want)
    ?? paints.find((p) => p.where === where)
  return { id, css: paint?.css ?? arch[id], where }
}

/**
 * The roles a catalogue variant MEANS to paint — mirrors `ButtonSpecimen`,
 * `BadgeSpecimen`, and `InlineAlertSpecimen` without re-deriving colours.
 * Measured paint css is kept on the swatch when present.
 */
export function resolveVariantRoles(
  t: PreviewTokens,
  componentKey: string,
  variant: Record<string, string>,
  paints: { css: string; where: PaintSlot }[],
): InspectedRole[] | null {
  const arch = t.archTokens
  if (!arch) return null

  if (componentKey === 'Button') {
    const intent = buttonIntent(variant.Color)
    const style = variant.Style ?? 'Solid'
    if (style === 'Solid') {
      if (intent === 'Brand') {
        const roles = [
          roleAt(arch, paints, 'action.primary.default', 'fill'),
          roleAt(arch, paints, 'content.on-action', 'ink'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
      const sev = STATUS_SEV[intent]
      if (sev) {
        const roles = [
          roleAt(arch, paints, `status.${sev}.surface-solid`, 'fill'),
          roleAt(arch, paints, `status.${sev}.on-solid`, 'ink'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
    }
    if (style === 'Soft') {
      if (intent === 'Brand') {
        const roles = [
          roleAt(arch, paints, 'action.ghost.brand.hover', 'fill'),
          roleAt(arch, paints, 'content.accent', 'ink'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
      const sev = STATUS_SEV[intent]
      if (sev) {
        const roles = [
          roleAt(arch, paints, `status.${sev}.surface`, 'fill'),
          roleAt(arch, paints, `status.${sev}.surface-solid`, 'ink'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
    }
    if (style === 'Outline' || style === 'Ghost') {
      const inkId = intent === 'Brand'
        ? 'content.accent'
        : STATUS_SEV[intent] ? `status.${STATUS_SEV[intent]}.content` : null
      if (!inkId) return null
      const ink = roleAt(arch, paints, inkId, 'ink')
      return ink ? [ink] : null
    }
  }

  if (componentKey === 'Badge') {
    const intent = variant.Color ?? 'Brand'
    const style = variant.Style ?? 'Soft'
    const isNeutral = intent === 'Neutral'
    if (style === 'Solid') {
      if (intent === 'Brand') {
        const roles = [
          roleAt(arch, paints, 'action.primary.default', 'fill'),
          roleAt(arch, paints, 'content.on-action', 'ink'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
      const sev = STATUS_SEV[intent]
      if (sev) {
        const roles = [
          roleAt(arch, paints, `status.${sev}.surface-solid`, 'fill'),
          roleAt(arch, paints, `status.${sev}.on-solid`, 'ink'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
    }
    if (style === 'Soft') {
      if (isNeutral) {
        const dotless = variant.Dot === 'False'
        const roles = [
          roleAt(arch, paints, 'surface.layer-1', 'fill'),
          roleAt(arch, paints, dotless ? 'content.primary' : 'content.secondary', 'ink'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
      const sev = STATUS_SEV[intent]
      if (sev) {
        // Soft paints THREE colours: the wash, the label, and the leading
        // status DOT (`statusColor` → `*.surface-solid`). Dropping the solid
        // left the inspector naming only the tint / content pair, so pointing
        // at Critical showed a coral swatch that was never the brown-red dot.
        const roles = [
          roleAt(arch, paints, `status.${sev}.surface`, 'fill'),
          roleAt(arch, paints, `status.${sev}.content`, 'ink'),
          roleAt(arch, paints, `status.${sev}.surface-solid`, 'fill'),
        ].filter((r): r is InspectedRole => !!r)
        return roles.length ? roles : null
      }
    }
    if (style === 'Outline') {
      const sev = STATUS_SEV[intent]
      const inkId = intent === 'Brand'
        ? 'content.accent'
        : sev ? `status.${sev}.surface-solid` : null
      if (!inkId) return null
      const ink = roleAt(arch, paints, inkId, 'ink')
      return ink ? [ink] : null
    }
  }

  if (componentKey === 'InlineAlert') {
    const status = variant.Status ?? 'Info'
    const sev = STATUS_SEV[status]
    if (!sev) return null
    const roles = [
      roleAt(arch, paints, `status.${sev}.surface`, 'fill'),
      roleAt(arch, paints, `status.${sev}.border`, 'stroke'),
      roleAt(arch, paints, 'content.primary', 'ink'),
      roleAt(arch, paints, 'content.secondary', 'ink'),
    ].filter((r): r is InspectedRole => !!r)
    return roles.length ? roles : null
  }

  if (componentKey === 'Toast') {
    const status = variant.Status ?? 'Success'
    const sev = STATUS_SEV[status]
    if (!sev) return null
    const roles = [
      roleAt(arch, paints, 'surface.inverse', 'fill'),
      roleAt(arch, paints, 'content.inverse', 'ink'),
      roleAt(arch, paints, `status.${sev}.surface-solid`, 'fill'),
    ].filter((r): r is InspectedRole => !!r)
    return roles.length ? roles : null
  }

  return null
}

/**
 * Ink is only painted where there are glyphs. `color` inherits, so every
 * wrapper in the subtree reports the page's text colour whether it renders a
 * character or not — which is how a Solid button ends up claiming
 * `content.primary` from the `Live` wrapper around it. A node with no direct
 * text node paints no ink.
 */
function paintsText(node: Element): boolean {
  for (const child of Array.from(node.childNodes)) {
    if (child.nodeType === 3 && (child.textContent ?? '').trim()) return true
  }
  return false
}

interface Observation { key: string; where: PaintSlot; css: string }

function observeNode(
  node: Element,
  out: Observation[],
  seen: Set<string>,
): void {
  const cs = getComputedStyle(node)
  // A `display: contents` marker generates no box, so it paints nothing —
  // reading it would attribute its inherited ink to the component.
  if (cs.display === 'contents') return
  const push = (css: string | null | undefined, where: PaintSlot) => {
    const key = normalizeColor(css)
    if (!key || !css) return
    const tag = `${key}|${where}`
    if (seen.has(tag)) return
    seen.add(tag)
    out.push({ key, where, css })
  }
  const masked = (cs.maskImage && cs.maskImage !== 'none') || (cs.webkitMaskImage && cs.webkitMaskImage !== 'none')
  // A masked span IS a glyph (see `PreviewIcon`): its background is the
  // icon's ink, not a surface fill.
  push(cs.backgroundColor, masked ? 'ink' : 'fill')
  if (paintsText(node)) push(cs.color, 'ink')
  for (const side of ['Top', 'Right', 'Bottom', 'Left'] as const) {
    const width = parseFloat(cs.getPropertyValue(`border-${side.toLowerCase()}-width`))
    if (!(width > 0)) continue
    if (cs.getPropertyValue(`border-${side.toLowerCase()}-style`) === 'none') continue
    push(cs.getPropertyValue(`border-${side.toLowerCase()}-color`), 'stroke')
  }
  if (parseFloat(cs.outlineWidth) > 0 && cs.outlineStyle !== 'none') push(cs.outlineColor, 'stroke')
}

/** Every colour the element and its descendants actually paint, in paint
 *  order — fill, then ink, then strokes, walking down the tree. */
function observePaints(root: Element): Observation[] {
  const out: Observation[] = []
  const seen = new Set<string>()
  const nodes = [root, ...Array.from(root.querySelectorAll('*')).slice(0, MAX_NODES)]
  for (const node of nodes) observeNode(node, out, seen)
  return out
}

/** Paints on the container itself — the card fill, its stroke — skipping
 *  anything already owned by a `[data-inspect]` child. Those children are
 *  measured separately so a button's green cannot be re-attributed as the
 *  module chrome. */
function observeChromePaints(root: Element): Observation[] {
  const out: Observation[] = []
  const seen = new Set<string>()
  const nodes = [root, ...Array.from(root.querySelectorAll('*')).slice(0, MAX_NODES)]
  for (const node of nodes) {
    if (node !== root && node.closest('[data-inspect]')) continue
    observeNode(node, out, seen)
  }
  return out
}

/**
 * Map observed paints back to role ids.
 *
 * `declared` is the component's field-closure union. When it is non-empty,
 * ONLY those ids may be reported — a hex that also belongs to an unrelated
 * role (`content.accent` sharing a button's fill, `surface.layer-1` sharing
 * a social-login well) must not sneak in. Falling through to every role
 * with that hex is what made Token Details open on a primitive that was
 * never the pixel you pointed at.
 *
 * The swatch is the MEASURED css, not `arch[id]`. Those two disagree the
 * moment a try-on overlay, an optimistic hue drag, or a hex collision is
 * in play; the badge has to show the colour on screen.
 */
export function rolesForPaints(
  arch: Record<string, string>,
  declared: string[],
  paints: { css: string; where: PaintSlot }[],
  fieldIndex?: Map<string, string[]>,
): InspectedRole[] {
  const index = roleIndex(arch)
  const roles: InspectedRole[] = []
  for (const paint of paints) {
    const key = normalizeColor(paint.css)
    if (!key) continue
    const fromArch = index.get(key) ?? []
    const fromField = fieldIndex?.get(key) ?? []
    const candidates = [...new Set([...fromArch, ...fromField])]
    if (!candidates.length) continue
    const owned = declared.length
      ? candidates.filter((id) => declared.includes(id))
      : candidates
    for (const id of owned) {
      if (roles.some((role) => role.id === id)) continue
      roles.push({ id, css: paint.css, where: paint.where })
    }
  }
  return roles
}

/**
 * A solid fill carries a paired ink. Button's declared union maps the
 * label of every Solid to `content.on-action` (`onBrand`), so a Danger
 * button's near-white ink was reported as the brand pair — and
 * `status.critical.on-solid` never appeared, even though that is what
 * `statusOn()` actually paints. Once the fill is a status/brand solid,
 * the badge lists that fill and its own on-ink, nothing else.
 */
const SOLID_INK: Record<string, string> = {
  'status.critical.surface-solid': 'status.critical.on-solid',
  'status.warning.surface-solid': 'status.warning.on-solid',
  'status.success.surface-solid': 'status.success.on-solid',
  'status.info.surface-solid': 'status.info.on-solid',
  'action.primary.default': 'content.on-action',
}

export function pairSolidRoles(
  arch: Record<string, string>,
  roles: InspectedRole[],
  paints: { css: string; where: PaintSlot }[],
): InspectedRole[] {
  const fill = Object.keys(SOLID_INK)
    .map((id) => roles.find((role) => role.where === 'fill' && role.id === id))
    .find((role): role is InspectedRole => !!role)
  if (!fill) return roles

  const inkId = SOLID_INK[fill.id]
  const inkPaint = paints.find((paint) => paint.where === 'ink')
  const out: InspectedRole[] = [{ ...fill, where: 'fill' }]
  if (inkId && arch[inkId] && inkPaint) {
    out.push({ id: inkId, css: inkPaint.css, where: 'ink' })
  }
  const fillKey = normalizeColor(fill.css)
  for (const role of roles) {
    if (role.where !== 'stroke') continue
    if (normalizeColor(role.css) === fillKey) continue
    out.push(role)
  }
  return out
}

/**
 * A Button is one fill and one label. Soft / Ghost / Outline / Pressed paint
 * a wash or a `darken()` that is not byte-identical to any role, so
 * `rolesForPaints` keeps the ink and drops the surface — or matches nothing
 * and the badge falls back to Button's whole union (solids of every severity).
 * Once a fill is actually on the element, the badge names that surface and
 * its label, nothing else: no outline, no leftover content roles.
 *
 * The wash still has a role. Translucent brand ink → the ghost ladder
 * (`hover` at ~10 %, `pressed` deeper); opaque `content.accent` → the
 * secondary accent fill Soft is. Solid on-ink → `action.primary.default`
 * unless the pixel already is hover/pressed.
 */
const INK_SURFACE: Record<string, string> = {
  'content.on-action': 'action.primary.default',
  'content.accent': 'action.secondary.accent',
  'content.primary': 'action.secondary.default',
  'status.critical.on-solid': 'status.critical.surface-solid',
  'status.warning.on-solid': 'status.warning.surface-solid',
  'status.success.on-solid': 'status.success.surface-solid',
  'status.info.on-solid': 'status.info.surface-solid',
}

function paintAlpha(css: string): number {
  const key = normalizeColor(css)
  if (!key) return 0
  return Number(key.slice(key.lastIndexOf(',') + 1))
}

function surfaceForInk(
  arch: Record<string, string>,
  inkId: string,
  fillCss: string,
): string | undefined {
  if (inkId === 'content.on-action') {
    const key = normalizeColor(fillCss)
    for (const id of ['action.primary.pressed', 'action.primary.hover', 'action.primary.default'] as const) {
      if (key && normalizeColor(arch[id]) === key) return id
    }
    return 'action.primary.default'
  }
  if (inkId === 'content.accent') {
    const a = paintAlpha(fillCss)
    if (a > 0 && a < 0.99) return a > 0.15 ? 'action.ghost.brand.pressed' : 'action.ghost.brand.hover'
    return 'action.secondary.accent'
  }
  return INK_SURFACE[inkId]
}

function firstArchId(
  arch: Record<string, string>,
  css: string,
  prefer: (id: string) => boolean,
): string | undefined {
  const key = normalizeColor(css)
  if (!key) return
  const candidates = roleIndex(arch).get(key) ?? []
  return candidates.find(prefer) ?? candidates[0]
}

export function pairButtonScopes(
  arch: Record<string, string>,
  roles: InspectedRole[],
  paints: { css: string; where: PaintSlot }[],
): InspectedRole[] {
  const fillPaint = paints.find((paint) => paint.where === 'fill')
  const inkPaint = paints.find((paint) => paint.where === 'ink')
  let fill = roles.find((role) => role.where === 'fill')
  let ink = roles.find((role) => role.where === 'ink')

  if (!ink && inkPaint) {
    const inkId = firstArchId(arch, inkPaint.css, (id) => id.startsWith('content.') || id.endsWith('.content') || id.endsWith('.on-solid'))
    if (inkId) ink = { id: inkId, css: inkPaint.css, where: 'ink' }
  }
  if (fill && !ink && inkPaint) {
    const fillId = fill.id
    const inkId = SOLID_INK[fillId] ?? Object.entries(INK_SURFACE).find(([, surface]) => surface === fillId)?.[0]
    if (inkId && arch[inkId]) ink = { id: inkId, css: inkPaint.css, where: 'ink' }
  }
  if (!fill && fillPaint) {
    const matched = firstArchId(
      arch,
      fillPaint.css,
      (id) => id.startsWith('action.') || id.includes('.surface'),
    )
    const inferred = ink ? surfaceForInk(arch, ink.id, fillPaint.css) : undefined
    const fillId = [matched, inferred, 'action.secondary.accent', 'action.primary.default']
      .find((id): id is string => !!id && !!arch[id])
    if (fillId) fill = { id: fillId, css: fillPaint.css, where: 'fill' }
  }

  const out: InspectedRole[] = []
  if (fill) out.push({ ...fill, where: 'fill' })
  if (ink) out.push({ ...ink, where: 'ink' })
  return out
}

/**
 * A TabMenu is a selected pill and the labels on it. The pill used to be
 * `soft(brandSolid)` — a wash that matched no role — so the badge kept
 * `content.secondary` (inactive tabs) and dropped the selection. Once a
 * fill is on the element, name `surface.selected` and the inks, nothing
 * else: no leftover brand solid from the specimen union.
 */
export function pairTabMenuScopes(
  arch: Record<string, string>,
  roles: InspectedRole[],
  paints: { css: string; where: PaintSlot }[],
): InspectedRole[] {
  const fillPaint = paints.find((paint) => paint.where === 'fill')
  let fill = roles.find((role) => role.where === 'fill' && role.id === 'surface.selected')
    ?? roles.find((role) => role.where === 'fill')
  if (!fill && fillPaint) {
    const matched = firstArchId(
      arch,
      fillPaint.css,
      (id) => id === 'surface.selected' || id.startsWith('action.ghost'),
    )
    const fillId = [matched, 'surface.selected'].find((id): id is string => !!id && !!arch[id])
    if (fillId) fill = { id: fillId, css: fillPaint.css, where: 'fill' }
  }

  const out: InspectedRole[] = []
  if (fill) out.push({ ...fill, where: 'fill' })
  for (const paint of paints) {
    if (paint.where !== 'ink') continue
    const existing = roles.find((role) => role.where === 'ink' && normalizeColor(role.css) === normalizeColor(paint.css))
    const inkId = existing?.id ?? firstArchId(arch, paint.css, (id) => id.startsWith('content.'))
    if (!inkId || out.some((role) => role.id === inkId)) continue
    out.push({ id: inkId, css: paint.css, where: 'ink' })
  }
  return out
}

/** Chrome fills/strokes prefer surface and border roles when several ids
 *  share the hex — a card should name `surface.layer-1`, not whatever
 *  action/content role happens to collide with it. */
function chromeIds(candidates: string[]): string[] {
  const preferred = candidates.filter((id) => id.startsWith('surface.') || id.startsWith('border.'))
  return preferred.length ? preferred : candidates
}

/**
 * The roles ONE rendered element paints, ordered the way it paints them.
 *
 * Falls back to the component's union (`measured: false`) when nothing
 * matched — a flat-architecture system has no `archTokens` at all, and a
 * specimen can legitimately paint only inherited or `transparent` colours.
 * An empty badge would read as "this component uses no colour", which is never
 * what happened.
 */
export function inspectElement(
  t: PreviewTokens, componentKey: string, el: Element,
): Inspection {
  const arch = t.archTokens
  if (!arch) return { roles: [], measured: false }
  const declared = rolesForComponent(componentKey)
  const paints = observePaints(el)
  const variant = parseInspectVariant(el)
  if (variant) {
    const explicit = resolveVariantRoles(t, componentKey, variant, paints)
    if (explicit?.length) return { roles: explicit, measured: true }
  }
  const fields = COMPONENT_COLOR_FIELDS[componentKey] ?? []
  const fieldIndex = fieldRoleIndex(t, fields)
  let roles = pairSolidRoles(arch, rolesForPaints(arch, declared, paints, fieldIndex), paints)
  if (componentKey === 'Button') {
    roles = pairButtonScopes(arch, roles, paints)
    // A Button answers with its surface and its label. Falling through to
    // the specimen's UNION would list every severity the axis can paint.
    return { roles, measured: true }
  }
  if (componentKey === 'TabMenu') {
    roles = pairTabMenuScopes(arch, roles, paints)
    return { roles, measured: true }
  }
  if (roles.length) return { roles, measured: true }
  return { roles: inspectComponent(t, componentKey), measured: false }
}

/**
 * The canvas the artefacts sit on. That fill is `surface.page` by contract
 * (`ThemePreviewHub`'s `pageCanvasColor`), not a measured paint — the scroll
 * container is transparent over the framed section that actually holds the
 * colour, so reading `backgroundColor` here would report nothing.
 */
export function inspectPage(t: PreviewTokens): Inspection {
  const css = t.archTokens?.['surface.page'] ?? t.pageBackground ?? t.surface
  if (!css) return { roles: [], measured: false }
  return {
    roles: [{ id: 'surface.page', css, where: 'fill' }],
    measured: true,
  }
}

/** A group's members and their combined roles. */
export interface GroupInspection {
  roles: InspectedRole[]
  /** Catalogue keys of the inspectable components inside, in DOM order. */
  members: string[]
}

/**
 * Every role painted by the components INSIDE a container — the answer to
 * "what does this whole cluster consume", which is the question you're asking
 * when you point at the box rather than at one control in it.
 *
 * Membership is read from the DOM (`[data-inspect]` descendants), never
 * declared on the container: a module that gains a component gains its roles
 * here with nothing to update, and a label listing components a module no
 * longer holds is impossible to write.
 */
export function inspectGroup(t: PreviewTokens, el: Element): GroupInspection {
  const members: string[] = []
  const roles: InspectedRole[] = []
  const arch = t.archTokens
  if (arch) {
    const index = roleIndex(arch)
    for (const paint of observeChromePaints(el)) {
      const candidates = index.get(paint.key)
      if (!candidates) continue
      for (const id of chromeIds(candidates)) {
        if (roles.some((existing) => existing.id === id)) continue
        roles.push({ id, css: paint.css, where: paint.where })
      }
    }
  }
  for (const child of Array.from(el.querySelectorAll('[data-inspect]'))) {
    const key = child.getAttribute('data-inspect') || ''
    if (!key) continue
    members.push(key)
    // Unmeasured children dump the component's WHOLE union — six variants
    // that aren't on screen. A GradientAvatar with a CSS gradient (no
    // `backgroundColor` to match) would otherwise inject `content.primary`
    // as the accent hex, which is the cyan swatch on a white heading.
    const inspection = inspectElement(t, key, child)
    if (!inspection.measured) continue
    for (const role of inspection.roles) {
      if (roles.some((existing) => existing.id === role.id)) continue
      roles.push(role)
    }
  }
  return { roles, members }
}
